### ISSUE TITLE
About the Turok series bug

### ISSUE THREAD

**Issue by itornukem64** [mupen64plus-ae/mupen64plus-ae#517] opened 2015-11-30 15:36 UTC
Hi, it seems like I've founded  the alpha where the games 2,3, rage wars are still playable,  or not so well I noticed thet in the alpha 6 the series are still playable but in the alpha 10 the games are broken already. 
So hope this can help you guys to fix the games

**Comment by itornukem64** [comment] 2015-12-03 14:15
I was testing the others alphas and the turok series stop working in alpha 8 but in alpha 7 are still working.

**Comment by fzurita** [comment] 2015-12-11 07:16
Have you tried the GLideN64 plugin?

**Comment by itornukem64** [comment] 2015-12-13 03:09
Oh yeah I tried and isn't working either,  oh and the glide64 plugin not work for me just black screen, x86 would this be the reason? 
This thing about the turok series is known, because in the forums is mentioned a couple of times, and I'm not a code master but I think is related with the new dynarec introduced in alpha 8

**Comment by fzurita** [comment] 2015-12-13 03:13
Have you tried there latest build from here? 

http://www.paulscode.com/source/Mupen64Plus-AE/AutoBuilds/

The one at the very top.

**Comment by itornukem64** [comment] 2015-12-13 15:09
I tried right now and again isn't working, the app just crashed

**Comment by fzurita** [comment] 2015-12-13 15:11
Do you have any files in this directory?

/sdcard/mupen64plusae-v3-alpha/CrashLogs

If the crash was at the front end, we can use that to figure out the cause.

**Comment by itornukem64** [comment] 2015-12-13 15:22
How can i post the log file?

**Comment by fzurita** [comment] 2015-12-13 15:25
You can copy the file to your PC open it in a text editor and post the contents here.

Alternatively, you could share using Google drive or any other file sharing service.

**Comment by itornukem64** [comment] 2015-12-13 15:50
I made a zip file because there are 3 logs http://upfile.mobi/1185545

**Comment by fzurita** [comment] 2015-12-13 16:00
Thanks, I will take a look.

**Comment by fzurita** [comment] 2015-12-13 16:10
Ok, I see the problem with your crash. Can you try this build?

https://drive.google.com/file/d/0B57Ioy26LWegNE85RFhXdnc1SGM/view?usp=sharing

You will have to uninstall your current version first.

**Comment by itornukem64** [comment] 2015-12-13 18:58
Yeeeaah! The games are now working flawlessly, but the Glide64 plugin is still just black screen, and i have a problem with the controller edit screen I can't  add buttons and exit from the controller edition screen,  I have to close the app.
And can you put the audio in the per games settings

**Comment by fzurita** [comment] 2015-12-13 19:02
You have to hit the back button in the controller edit screen to bring up the menu.

The GLideN64 plugin works for you though? I'm not sure what is wrong with the Glide64 plugin.

**Comment by fzurita** [comment] 2015-12-13 19:05
I just tried the Glide64 plugin and it works for me, at least in turok 2. What phone do you have?

**Comment by itornukem64** [comment] 2015-12-13 19:28
Well maybe, because is x86, it's a Samsung galaxy tab 3 10.1 or it could be related with the flicker reduction?. And that is just the problem i hit the back button but it doesn't bring up the menu, don't know why.

**Comment by fzurita** [comment] 2015-12-13 19:32
Ok, it does have PowerVR graphics. That could be the reason. Hmmm, interesting, so the back key doesn't do anything for you.

I think I know what the problem is. I'll try to come up with a fix.

**Comment by itornukem64** [comment] 2015-12-13 19:39
Ok and thanks, and please add the audio option to the per games settings.

**Comment by fzurita** [comment] 2015-12-13 19:40
Which specific audio options do you think should be a per game setting?

**Comment by itornukem64** [comment] 2015-12-13 19:49
The mupen64plus-audio-sles, v2.0 one

**Comment by fzurita** [comment] 2015-12-13 20:00
Any specific reason why you set audio options that are different for each game?

**Comment by itornukem64** [comment] 2015-12-13 22:35
Well the speed of the emulation XD In some games with the sound the emulation speed is good but in some others the speed decreases or is laggy so is better off

**Comment by fzurita** [comment] 2015-12-13 22:36
Gotcha, personally I don't enjoy playing games without sound :P

I'll see what I can do.

**Comment by itornukem64** [comment] 2015-12-13 22:43
Yeah, i know it loses some fun :v

**Comment by fzurita** [comment] 2015-12-18 13:19
The touch screen profile editor should be fixed in the latest auto build.

**Comment by itornukem64** [comment] 2015-12-18 14:51
Yes is fixed now, so i think this is closed now, right?

**Closed** 2015-12-19 07:21 UTC
