### ISSUE TITLE
Zelda Ocarina Of Time

### ISSUE THREAD

**Issue by zeldaismygame1221** [mupen64plus-ae/mupen64plus-ae#457] opened 2015-09-21 20:33 UTC
Okay i was playing it when all of a sudden the screen freezes..the frames stopped but the audio was still going..i restarted the game. Went back to my saved slot and it was fixed. Now im at the spirit temple having the same issue..although this time its not working. I tryed playing other downloaded games, other apps i purchased and came back to see if it would debug itself but its still not working...any suggestions on what to do without deleting all of my saved data??

**Comment by easyaspi314** [comment] 2015-09-22 11:00
Can you provide info?

*App version
*Plugins (audio, video, interpreter)
*Phone info (you can find that in the app in help or about.

Also, try this:
*Switch plugins. Usually video.
*When it freezes, press menu, game speed and cancel. It forces an update.

**Comment by Gillou68310** [comment] 2015-10-01 08:02
Duplicate of https://github.com/mupen64plus-ae/mupen64plus-ae/issues/376
Please test with this build https://www.dropbox.com/s/185rjbaseidtcjv/SplashActivity.apk?dl=0

**Closed by Gillou68310** 2015-10-01 08:02 UTC
