### ISSUE TITLE
in dk64 why cant i get the dk coins

### ISSUE THREAD

**Issue by sammybam88** [mupen64plus-ae/mupen64plus-ae#855] opened 2020-09-08 16:55 UTC
in the training barrels I need to get them but donkey kong won't pick them up he just goes through

**Comment by fzurita** [comment] 2020-09-08 17:05
Are you using any cheats?

**Comment by sammybam88** [comment] 2020-09-08 17:08
no and it still won't collect

**Comment by fzurita** [comment] 2020-09-08 17:27
Which version of the game are you using?

**Comment by fzurita** [comment] 2020-11-14 18:57
I'm unable to reproduce this issue. Is this in the beginning area?

**Comment by fzurita** [comment] 2020-11-15 04:32
Closing unless I get a response.

**Closed by fzurita** 2020-11-15 04:32 UTC
