### ISSUE TITLE
heeeeeeelp

### ISSUE THREAD

**Issue by rancher-zz** [mupen64plus-ae/mupen64plus-ae#378] opened 2014-01-18 04:42 UTC
I was playing zelda oot, and it froze so i decided to save it , then whenever i load my save it freezes and only plays water sounds. HEELP, I GOT SOOO FAR,!

**Comment by Gillou68310** [comment] 2015-10-01 08:04
Duplicate of https://github.com/mupen64plus-ae/mupen64plus-ae/issues/376

**Closed by Gillou68310** 2015-10-01 08:04 UTC
