### ISSUE TITLE
Use of fingerprint button ?

### ISSUE THREAD

**Issue by Jef2i** [mupen64plus-ae/mupen64plus-ae#602] opened 2016-12-04 10:18 UTC
I recently gave a try to this emulator. Awesome work men !
But I must admit that it's really difficult to play some games using complex buttons combinations on a smartphone touchscreen.
I've got Ocarina in my mind where a common one is a Z+Analog+B.
I've got a fingerprint button on the rear of my smartphone. It can be pushed but also touched and swiped.
Tried to look around into M64+FZ settings but didn't find any way to configure it. So I believe a particular "controller profile" may be needed for this.

**Comment by fzurita** [comment] 2016-12-04 12:16
That's not a bad idea actually. I'll look into this.

**Comment by Jef2i** [comment] 2016-12-04 18:15
Cool :)
Let me know for help (device infos, feedbacks, ...)

**Comment by fzurita** [comment] 2017-01-06 03:15
Unfortunately, I'm not finding an easy way to do this. I'll keep this open until an easier way becomes available.

**Comment by fzurita** [comment] 2017-06-08 21:38
Look like Android O (8.0) is adding official support for fingerprint gestures!

https://developer.android.com/preview/api-overview.html

**Comment by BAM5** [comment] 2019-01-30 21:53
Any plans to implement?

**Comment by fzurita** [comment] 2019-01-30 22:05
The issue is still open, so yeah, if there is enough requests for it. Right now it's lower priority. There is an API for this, but not all phones support it:

https://developer.android.com/reference/android/accessibilityservice/FingerprintGestureController

**Comment by BAM5** [comment] 2019-01-30 23:58
I was trying to map z to just touch. Gestures would be a nice touch, but all it really needs is the pressed / not pressed functionality.

Anyway, would love to see this feature, would definitely make using touch controls better. Especially for phone's with the scanner on the back (one plus 5t & 6, Galaxy s8 s9, etc)

**Comment by fzurita** [comment] 2020-11-14 19:08
This is still not feasible because Android has not implemented a proper API for this. I'm going to go ahead and close it. If a proper API shows up, then a new issue can be made.

**Closed by fzurita** 2020-11-14 19:08 UTC
