### ISSUE TITLE
Mario Party 2 not working.

### ISSUE THREAD

**Issue by Oofboi2020** [mupen64plus-ae/mupen64plus-ae#820] opened 2020-05-14 11:57 UTC
For some reason it appears for a millisecond and disappears. I tried putting the rom in the Unzipped roms folder, still no result.

**Comment by fzurita** [comment] 2020-05-14 15:28
What version of the app are you using? It should be this one: https://play.google.com/store/apps/details?id=org.mupen64plusae.v3.fzurita

Others are out of date or clones that are out of date.

**Comment by Oofboi2020** [comment] 2020-05-16 13:31
Mupen FZ.

**Comment by fzurita** [comment] 2020-05-16 14:26
Unzipped ROM folder is not used by the app anymore. ROMs are extracted on the fly. It's possible that you don't have a valid ROM. What is the extension on the file?

**Comment by Oofboi2020** [comment] 2020-05-16 14:31
Z64

**Comment by fzurita** [comment] 2020-05-16 14:40
It's possible your device didn't have enough RAM to load the ROM or the ROM is corrupted in some way. What device do you have?

**Comment by Oofboi2020** [comment] 2020-05-16 14:42
Samsung Galaxy A10, runs perfectly for other games.

**Comment by Oofboi2020** [comment] 2020-05-16 14:45
Also, I got the rom from Vimm's lair, which is weird because OoT works and
it was from Vimm's lair.

**Comment by fzurita** [comment] 2020-05-16 14:45
Try changing the emulation profile. Select the game, go to settings, and change the emulation profile to GLideN64-Medium.

If that doesn't work. I would try obtaining a different copy of the game, it's possible that the one you have is corrupt. Mario party 2 works here without any issue.

I tried that game here and it works just fine.

**Comment by Oofboi2020** [comment] 2020-05-17 20:59
I think I had opened it previously without going into my library via opening the rom and setting to app to open as mupen64 fz.

**Comment by fzurita** [comment] 2020-11-15 04:29
Closing since I can't reproduce.

**Closed by fzurita** 2020-11-15 04:29 UTC
