### ISSUE TITLE
Crash when starting a game

### ISSUE THREAD

**Issue by Gillou68310** [mupen64plus-ae/mupen64plus-ae#592] opened 2016-10-13 08:49 UTC
When using latest master I'm experiencing a lot of crash when starting a game. This usually happens when stopping a game and starting a new one. My guess is that something is going wrong in the shutdown process. Going back to pre_android_studio branch fixes the issue.

**Comment by fzurita** [comment] 2016-10-13 11:37
Yeah, I do see that as well. I did recently add a shutdown thread, it maybe related to that.

**Comment by fzurita** [comment] 2016-10-13 11:56
I don't think that the unloadLibraries is really cleaning up all the C/C++ libraries very well. It's leaving something behind that is staying between runs.

**Comment by fzurita** [comment] 2016-10-13 12:23
It could be happening because of this:
https://github.com/mupen64plus-ae/mupen64plus-ae/commit/1eb3866c20af6728eb346ce5c3c447ccb744e60c

I'm not quite sure there could be causing it though.

**Comment by fzurita** [comment] 2016-10-13 12:31
I'm also worried that it could be caused by this:
https://github.com/mupen64plus/mupen64plus-core/commit/bbf2d25e9e90bd96a305aa113f65aaad1889c762

**Comment by Gillou68310** [comment] 2016-10-13 13:03
> I'm also worried that it could be caused by this:
> mupen64plus/mupen64plus-core@bbf2d25

That's very unlikely because I don't have this issue with the pre_android_studio branch.

**Comment by fzurita** [comment] 2016-10-13 13:05
OK, that rules that out. It's probably the shutdown thread causing it. I'll revert those changes and figure out a better way.

**Comment by fzurita** [comment] 2016-10-13 22:23
The correct way to do this in the end will be to use a service. The whole thread thing is very hacky for Android.

**Comment by fzurita** [comment] 2016-10-15 12:28
I reverted that change but I can see why it was crashing now. CoreInterface is hanging on to the GameActivity and GameSurface after they both have been destroyed.

**Comment by Gillou68310** [comment] 2016-10-15 13:57
Thanks for the details ;-)

> The correct way to do this in the end will be to use a service.

If you have time to work on it, I think it's definitely the way to go!

**Comment by fzurita** [comment] 2016-10-18 15:36
This seems to be fixed now.

**Closed by fzurita** 2016-10-18 15:36 UTC
